### ISSUE TITLE
Missing container_exporter/Dockerfile

### ISSUE THREAD

**Issue by jvasile** [andreaskoch/docker-prometheus-monitoring#1]
Docker complains it can't build because of a missing Dockerfile. The container_exporter directory is indeed empty.

**Comment by andreaskoch** [comment]
The `container_exporter` folder is reference to another git repository ([github.com/docker-infra/container_exporter](https://github.com/docker-infra/container_exporter/)).

To clone my repository directly with the submodule you can use the `--recursive` flag of git clone command:

``` bash
git clone --recursive git@github.com:andreaskoch/docker-prometheus-monitoring.git
```

After that your repository folder should look something like this:

```
.
├── container_exporter
│   ├── devicemap.go
│   ├── Dockerfile
│   ├── docker_manager.go
│   ├── exporter.go
│   ├── main.go
│   ├── manager.go
│   ├── README.md
│   └── _vendor
├── fig.yml
├── files
│   └── screenshots
├── prometheus.conf
└── README.md
```

If you have cloned the repository without the `--recursive` flag you can use:

``` bash
git submodule update --init --recursive
```

to download the submodule afterwards.

Greetings
Andy

**Comment by andreaskoch** [comment]
Thanks for pointing that out to me. It was not obvious that the repository was using a git submodule.
I updated the [README](https://github.com/andreaskoch/docker-prometheus-monitoring/commit/da4b3ade15c744c243c1c5c371b18c7b6857d9bd) and added a "Installation" section.

**Comment by jvasile** [comment]
Issue solved. Many thanks.
